#pragma once

#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"

// Queue to hold ASCII characters generated by the BLE keyboard
extern QueueHandle_t keyboard_char_queue;

void keyboard_init(void);
void keyboard_process(void);